#generated on Fri Oct 25 02:02:22 CEST 2013
CC=gcc
COFFEE=coffee
UGLIFY=closure
prefix=/usr/local
DESTDIR=
PREFIX=$(DESTDIR)$(prefix)
OS=-DUNIX
#DEVEL=-DDEVEL
SDLFLAGS=-I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
#SOUND=-DSOUND
OPENGL=-DOPENGL
CFLAGS=-O2 $(SDLFLAGS) $(OS) $(DEVEL) $(SOUND) $(OPENGL)
WORKDIR=$(PREFIX)/games/oki
CLIBS=-L/usr/lib -lSDL -lpthread -lSDL_image -lGL
