#generated on nie maj 14 12:52:14 CEST 2006
CC=gcc
prefix=/root/usr
DESTDIR=
PREFIX=$(DESTDIR)$(prefix)
OS=-DUNIX
#DEVEL=-DDEVEL
SDLFLAGS=-I/usr/include/SDL -D_REENTRANT
SOUND=-DSOUND
OPENGL=-DOPENGL
CFLAGS=-O2 $(SDLFLAGS) $(OS) $(DEVEL) $(SOUND) $(OPENGL)
WORKDIR=$(PREFIX)/games/oki
CLIBS=-lSDL -lpthread -lSDL_image -lSDL_mixer -lGL
