include ../Makefile.global

all:

clean:
	rm -f oki_log

install:
	mkdir -p $(PREFIX)/bin
	cp -f oki_bash $(PREFIX)/bin/oki
	mkdir -p $(PREFIX)/share/applications
	cp -f oki.desktop $(PREFIX)/share/applications
